AWSTemplateFormatVersion: 2010-09-09

Description: This CloudFormation stack is to deploy a Parsec Gaming Rig

Parameters:
  DefaultRootEbsSize:
    Type: Number
    Default: 100
    MinValue: 100

Mappings: 
  RegionMap: 
    us-east-1: # US N.Virginia
      "g22xlarge": "ami-0ba87cc8e572325ab"
      "g34xlarge": "ami-0013cc8e269db9d05"
      "g4dnxlarge": "ami-04c1243d5dbdff11c"
    us-west-1: # US N.California
      "g22xlarge": "ami-0acf095c69cef033e"
      "g34xlarge": "ami-07d24e8eedcf2ac54"
      "g4dnxlarge": "ami-00bc6654cc803f82d"
    us-west-2: # US Oregon
      "g22xlarge": "ami-0bf6c9bb173cc453a"
      "g34xlarge": "ami-0f1ed563a9b7a23e6"
      "g4dnxlarge": "ami-05bf5932c8f07c8ae"
    eu-central-1: # Frankfurt
      "g22xlarge": "ami-0727d5b8187c84983"
      "g34xlarge": "ami-099300d88c891f63e"
      "g4dnxlarge": "ami-0914e9e13cdb9f240"
    eu-west-1: # Ireland
      "g22xlarge": "ami-0d22df4c98a4e7bca"
      "g34xlarge": "ami-030eaeb31ddb230e9"
      "g4dnxlarge": "ami-01bcf22b17ad79898"
    ap-southeast-1: # Singapore
      "g22xlarge": "ami-0268e84bc5bad384d"
      "g34xlarge": "ami-000cfbbdfd068adfa"
    ap-southeast-2: # Sydney
      "g22xlarge": "ami-03f986fe673a2e521"
      "g34xlarge": "ami-0cb2a24332175456a"
    ap-northeast-1:  # Tokyo
      "g22xlarge": "ami-0840cacb94f47423e"
      "g34xlarge": "ami-060d4f0550d79b625"
      "g4dnxlarge": "ami-03f39bdf9ff88f7d9"

Conditions:
  NotInSydney:
    !Not [!Equals [!Ref "AWS::Region", "ap-southeast-2"]]
  NotInSingapore:
    !Not [!Equals [!Ref "AWS::Region", "ap-southeast-1"]]
  IsG4InstanceAvailable:
    !And [Condition: NotInSingapore, Condition: NotInSydney]

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ParsecGamingRigSecurityGroup
      GroupDescription: Parsec Gaming Rig Security Group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 5900
          ToPort: 5900
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 3389
          ToPort: 3389
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 8000
          ToPort: 8005
          IpProtocol: udp

  g22xlargeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: g2.xlarge
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "g22xlarge"]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !Ref DefaultRootEbsSize
      LaunchTemplateName: "g2.2xlarge-ParsecGamingRig"

  g34xlargeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: g3.4xlarge
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "g34xlarge"]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !Ref DefaultRootEbsSize
      LaunchTemplateName: "g3.4xlarge-ParsecGamingRig"

  g4dnXlargeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Condition: IsG4InstanceAvailable
    Properties: 
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: g4dn.xlarge
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "g4dnxlarge"]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !Ref DefaultRootEbsSize
      LaunchTemplateName: "g4dn.xlarge-ParsecGamingRig"

  g22xlargeLaunchTemplateSpot:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: g2.xlarge
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "g22xlarge"]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !Ref DefaultRootEbsSize
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            InstanceInterruptionBehavior: stop
            SpotInstanceType: persistent
      LaunchTemplateName: "Spot-g2.2xlarge-ParsecGamingRig"

  g34xlargeLaunchTemplateSpot:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: g3.4xlarge
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "g34xlarge"]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !Ref DefaultRootEbsSize
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            InstanceInterruptionBehavior: stop
            SpotInstanceType: persistent
      LaunchTemplateName: "Spot-g3.4xlarge-ParsecGamingRig"
  
  g4dnXlargeLaunchTemplateSpot:
    Type: AWS::EC2::LaunchTemplate
    Condition: IsG4InstanceAvailable
    Properties: 
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: g4dn.xlarge
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "g4dnxlarge"]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !Ref DefaultRootEbsSize
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            InstanceInterruptionBehavior: stop
            SpotInstanceType: persistent
      LaunchTemplateName: "Spot-g4dn.xlarge-ParsecGamingRig"
